In [2]:
import numpy as np

arr1=np.array([10,20,30,40])
arr2=np.array([1,2,3,4])

In [3]:
arr1+arr2

array([11, 22, 33, 44])

In [4]:
arr1-arr2

array([ 9, 18, 27, 36])

In [5]:
arr2*2

array([2, 4, 6, 8])

In [6]:
arr2**2

array([ 1,  4,  9, 16])

In [7]:
arr1*arr2

array([ 10,  40,  90, 160])

In [8]:
arr1/arr2

array([10., 10., 10., 10.])

In [11]:
arr1/(arr2**2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [12]:
arr1>20

array([False, False,  True,  True])

In [13]:
arr3=np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [14]:
[arr3.sum(),arr3.mean()]

[np.int64(10), np.float64(2.0)]

In [15]:
[arr3.std(),arr3.var()]

[np.float64(1.4142135623730951), np.float64(2.0)]

In [16]:
[arr3.min(),arr3.max()]

[np.int64(0), np.int64(4)]

In [17]:
arr4=np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [18]:
arr4.cumsum()

array([ 1,  3,  6, 10])

In [19]:
arr4.cumprod()

array([ 1,  2,  6, 24])

In [20]:
A=np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [21]:
B=np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [22]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [24]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [25]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [26]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [27]:
np.linalg.det(A)

np.float64(-2.0)

In [28]:
a1=np.array([0,10,20,30,40,50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [29]:
a1[0]

np.int64(0)

In [30]:
a1[-2]

np.int64(40)

In [31]:
a1[5]=70
a1

array([ 0, 10, 20, 30, 40, 70])

In [32]:
a1[[1,3,4]]

array([10, 30, 40])

In [34]:
a2=np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [36]:
a2[0,2]

np.int64(30)

In [37]:
a2[2,2]=95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [38]:
a2[1]

array([40, 50, 60])

In [39]:
a2[1]=np.array([45,55,65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [40]:
a2[1]=[47,57,69]
a2

array([[10, 20, 30],
       [47, 57, 69],
       [70, 80, 95]])

In [41]:
a2[[0,2],[0,1]]

array([10, 80])

In [42]:
a=np.array([1,2,3,4,5,6])
a[a>3]

array([4, 5, 6])

In [43]:
a[(a%2)==0]

array([2, 4, 6])

In [45]:
b1=np.array([0,10,20,30,40,50])
b1[1:4]

array([10, 20, 30])

In [47]:
b1[2:]

array([20, 30, 40, 50])

In [48]:
b1[2:5]=np.array([25,34,45])
b1

array([ 0, 10, 25, 34, 45, 50])

In [49]:
b1[3:6]=60
b1

array([ 0, 10, 25, 60, 60, 60])

In [50]:
b2=np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [51]:
b2[1:3,1:3]

array([[50, 60],
       [80, 90]])

In [52]:
b2[:3,1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [53]:
b2[1][0:2]

array([40, 50])

In [54]:
b2[0:2,1:3]=np.array([[25,35],[55,65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])