In [1]:
import numpy as np

data1=[0,1,2,3,4,5]
a1=np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [2]:
data2=[0.1,5,4,12,0.5]
a2=np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [3]:
a1.dtype

dtype('int64')

In [4]:
a2.dtype

dtype('float64')

In [5]:
np.array([0.5,2,0.01,8])

array([0.5 , 2.  , 0.01, 8.  ])

In [6]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [10]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
b2=np.arange(5)

In [12]:
b2.shape

(5,)

In [13]:
np.linspace(0,np.pi,20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.array(['1.5','0.62','2','3.14','3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [19]:
str_a1=np.array(['1.567','0.123','5.123','9','8'])
num_a1=str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [20]:
str_a1.dtype

dtype('<U5')

In [21]:
num_a1.dtype

dtype('float64')

In [22]:
num_f1=np.array([10,21,0.549,4.75,5.98])
num_i1=num_f1.astype(int)
num_i1

array([10, 21,  0,  4,  5])

In [23]:
num_f1.dtype

dtype('float64')

In [24]:
num_i1.dtype

dtype('int64')

In [25]:
np.random.rand(2,3)

array([[0.51615806, 0.12768733, 0.48407532],
       [0.01626947, 0.15513059, 0.50167748]])

In [26]:
np.random.rand()

0.49603420821243405

In [27]:
np.random.rand()

0.623127523203387

In [28]:
np.random.rand(2,3,4)

array([[[0.97646244, 0.87819186, 0.42384395, 0.55077264],
        [0.72413287, 0.36564533, 0.58666534, 0.19033486],
        [0.50632533, 0.96872993, 0.96069479, 0.87255729]],

       [[0.76049249, 0.77522685, 0.09389975, 0.25896686],
        [0.59806074, 0.70048045, 0.89244804, 0.48812491],
        [0.62321511, 0.03713196, 0.44135713, 0.70057829]]])

In [29]:
np.random.randint(10,size=(3,4))

array([[2, 8, 8, 7],
       [1, 3, 4, 7],
       [7, 6, 6, 3]], dtype=int32)

In [30]:
np.random.randint(1,30)

10

division by zero
