In [1]:
import pandas as pd


In [2]:
s1=pd.Series([10,20,30,40,50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [3]:
s1.index
print(s1.index)

RangeIndex(start=0, stop=5, step=1)


In [4]:
s1.values

array([10, 20, 30, 40, 50])

In [5]:
s2=pd.Series(['a','b','c',1,2,3])
s2

0    a
1    b
2    c
3    1
4    2
5    3
dtype: object

In [6]:
import numpy as np

s3=pd.Series([np.nan,10,30])
s3

0     NaN
1    10.0
2    30.0
dtype: float64

In [7]:
index_date=['2025-08-07','2025-10-08','2025-10-09','2025-10-10']
s4=pd.Series([200,195,np.nan,205],index=index_date)
s4

2025-08-07    200.0
2025-10-08    195.0
2025-10-09      NaN
2025-10-10    205.0
dtype: float64

In [10]:
s5=pd.Series({'국어':100,'영어':95,'수학':90})
s5

국어    100
영어     95
수학     90
dtype: int64

In [11]:
import pandas as pd


In [12]:
pd.date_range(start='2025-01-01',end='2025-01-07')

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07'],
              dtype='datetime64[ns]', freq='D')

In [13]:
pd.date_range(start='2025/01/01',end='2025.01.07')

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07'],
              dtype='datetime64[ns]', freq='D')

In [14]:
pd.date_range(start='01-01-2025',end='01/07/2025')

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07'],
              dtype='datetime64[ns]', freq='D')

In [15]:
pd.date_range(start='2025-01-01',end='01.07.2025')

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07'],
              dtype='datetime64[ns]', freq='D')

In [16]:
pd.date_range(start='2025-01-01',periods=7)

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07'],
              dtype='datetime64[ns]', freq='D')

In [17]:
pd.date_range(start='2025-01-01',periods=4,freq='2D')

DatetimeIndex(['2025-01-01', '2025-01-03', '2025-01-05', '2025-01-07'], dtype='datetime64[ns]', freq='2D')

In [18]:
pd.date_range(start='2025-01-01',periods=4,freq='W')

DatetimeIndex(['2025-01-05', '2025-01-12', '2025-01-19', '2025-01-26'], dtype='datetime64[ns]', freq='W-SUN')

In [19]:
pd.date_range(start='2025-01-01',periods=12,freq='2BME')

DatetimeIndex(['2025-01-31', '2025-03-31', '2025-05-30', '2025-07-31',
               '2025-09-30', '2025-11-28', '2026-01-30', '2026-03-31',
               '2026-05-29', '2026-07-31', '2026-09-30', '2026-11-30'],
              dtype='datetime64[ns]', freq='2BME')

In [20]:
pd.date_range(start='2025-01-01',periods=4,freq='QS')

DatetimeIndex(['2025-01-01', '2025-04-01', '2025-07-01', '2025-10-01'], dtype='datetime64[ns]', freq='QS-JAN')

In [21]:
pd.date_range(start='2025-01-01',periods=3,freq='YS')

DatetimeIndex(['2025-01-01', '2026-01-01', '2027-01-01'], dtype='datetime64[ns]', freq='YS-JAN')

In [22]:
pd.date_range(start='2025-01-01 08:00',periods=10,freq='h')

DatetimeIndex(['2025-01-01 08:00:00', '2025-01-01 09:00:00',
               '2025-01-01 10:00:00', '2025-01-01 11:00:00',
               '2025-01-01 12:00:00', '2025-01-01 13:00:00',
               '2025-01-01 14:00:00', '2025-01-01 15:00:00',
               '2025-01-01 16:00:00', '2025-01-01 17:00:00'],
              dtype='datetime64[ns]', freq='h')

In [23]:
pd.date_range(start='2025-01-01',periods=10,freq='bh')

DatetimeIndex(['2025-01-01 09:00:00', '2025-01-01 10:00:00',
               '2025-01-01 11:00:00', '2025-01-01 12:00:00',
               '2025-01-01 13:00:00', '2025-01-01 14:00:00',
               '2025-01-01 15:00:00', '2025-01-01 16:00:00',
               '2025-01-02 09:00:00', '2025-01-02 10:00:00'],
              dtype='datetime64[ns]', freq='bh')

In [24]:
pd.date_range(start='2025-01-01 10:00',periods=4,freq='30min')

DatetimeIndex(['2025-01-01 10:00:00', '2025-01-01 10:30:00',
               '2025-01-01 11:00:00', '2025-01-01 11:30:00'],
              dtype='datetime64[ns]', freq='30min')

In [25]:
pd.date_range(start='2025-01-01',periods=4,freq='30min')

DatetimeIndex(['2025-01-01 00:00:00', '2025-01-01 00:30:00',
               '2025-01-01 01:00:00', '2025-01-01 01:30:00'],
              dtype='datetime64[ns]', freq='30min')

In [26]:
pd.date_range(start='2025-01-01  10:00:00',periods=4,freq='10s')

DatetimeIndex(['2025-01-01 10:00:00', '2025-01-01 10:00:10',
               '2025-01-01 10:00:20', '2025-01-01 10:00:30'],
              dtype='datetime64[ns]', freq='10s')

In [27]:
index_date=pd.date_range(start='2025-03-01',periods=5,freq='D')
pd.Series([51,62,55,49,58],index=index_date)

2025-03-01    51
2025-03-02    62
2025-03-03    55
2025-03-04    49
2025-03-05    58
Freq: D, dtype: int64

In [28]:
import pandas as pd
pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [29]:
import numpy as np
import pandas as pd

data_list=np.array([[10,20,30],[40,50,60],[70,80,90]])
pd.DataFrame(data_list)

0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [32]:
table_data={"연도":[2015,2016,2016,2017,2017],
            "지사":["한국","한국","미국","한국","미국"],
            "고객수":[200,250,450,300,500]}
table_data

{'연도': [2015, 2016, 2016, 2017, 2017],
 '지사': ['한국', '한국', '미국', '한국', '미국'],
 '고객수': [200, 250, 450, 300, 500]}

In [33]:
pd.DataFrame(table_data)

연도  지사  고객수
0  2015  한국  200
1  2016  한국  250
2  2016  미국  450
3  2017  한국  300
4  2017  미국  500

In [34]:
df=pd.DataFrame(table_data,columns=['연도','지사','고객수'])
df

연도  지사  고객수
0  2015  한국  200
1  2016  한국  250
2  2016  미국  450
3  2017  한국  300
4  2017  미국  500

In [35]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [36]:
df.columns

Index(['연도', '지사', '고객수'], dtype='object')

In [37]:
df.values

array([[2015, '한국', 200],
       [2016, '한국', 250],
       [2016, '미국', 450],
       [2017, '한국', 300],
       [2017, '미국', 500]], dtype=object)

In [38]:
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([10,20,30,40,50])
s1+s2

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [39]:
s2-s1

0     9
1    18
2    27
3    36
4    45
dtype: int64

In [40]:
s1*s2

0     10
1     40
2     90
3    160
4    250
dtype: int64

In [41]:
s2/s1

0    10.0
1    10.0
2    10.0
3    10.0
4    10.0
dtype: float64

In [52]:
s3=pd.Series([1,2,3,4])
s4=pd.Series([10,20,30,40,50])



In [53]:
s3+s4

0    11.0
1    22.0
2    33.0
3    44.0
4     NaN
dtype: float64

In [54]:
s4-s3

0     9.0
1    18.0
2    27.0
3    36.0
4     NaN
dtype: float64

In [55]:
s3*s4

0     10.0
1     40.0
2     90.0
3    160.0
4      NaN
dtype: float64

In [56]:
s4/s3

0    10.0
1    10.0
2    10.0
3    10.0
4     NaN
dtype: float64

In [57]:
table_data1={'A':[1,2,3,4,5],
             'B':[10,20,30,40,50],
             'C':[100,200,300,400,500]}
df1=pd.DataFrame(table_data1)
df1

A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [48]:
table_data2={"A":[6,7,8],
             "B":[60,70,80],
             "C":[600,700,800]}
df2=pd.DataFrame(table_data2)
df2

A   B    C
0  6  60  600
1  7  70  700
2  8  80  800

In [49]:
df1+df2

A      B       C
0   7.0   70.0   700.0
1   9.0   90.0   900.0
2  11.0  110.0  1100.0
3   NaN    NaN     NaN
4   NaN    NaN     NaN

In [59]:
table_data3={"봄":[256.5,264.3,215.9,223.2,312.8],
             "여름":[770.6,567.5,599.8,387.1,446.2],
             "가을":[363.5,231.2,293.1,247.7,381.6],
             "겨울":[139.3,59.9,76.9,109.1,108.1]}

columns_list=['봄','여름','가을','겨울']
index_list=['2012','2013','2014','2015','2016']

df3=pd.DataFrame(table_data3,columns=columns_list,index=index_list)
df3
             

봄     여름     가을     겨울
2012  256.5  770.6  363.5  139.3
2013  264.3  567.5  231.2   59.9
2014  215.9  599.8  293.1   76.9
2015  223.2  387.1  247.7  109.1
2016  312.8  446.2  381.6  108.1

In [60]:
df3.mean()

봄     254.54
여름    554.24
가을    303.42
겨울     98.66
dtype: float64

In [61]:
df3.std()

봄      38.628267
여름    148.888895
가을     67.358496
겨울     30.925523
dtype: float64

In [62]:
df3.mean(axis=1)

2012    382.475
2013    280.725
2014    296.425
2015    241.775
2016    312.175
dtype: float64

In [63]:
df3.std(axis=1)

2012    274.472128
2013    211.128782
2014    221.150739
2015    114.166760
2016    146.548658
dtype: float64

In [64]:
df.describe()

연도         고객수
count     5.00000    5.000000
mean   2016.20000  340.000000
std       0.83666  129.421791
min    2015.00000  200.000000
25%    2016.00000  250.000000
50%    2016.00000  300.000000
75%    2017.00000  450.000000
max    2017.00000  500.000000

In [71]:
import pandas as pd
import numpy as np

KTX_data = {
    "경부선 KTX":[39060,39896,42005,43621,41702,41266, np.nan],
    "호남선 KTX":[7313,6967,6876,6654,5589,10622,9228],
    "경전선 KTX":[3612,6589,6587,6597,9898,6565,9587],
    "전라선 KTX":[309,1771,1954,2244,3146,3945,5766],
    "동해선 KTX":[np.nan,np.nan,np.nan,np.nan,2395,3786,6667]
}

col_list = ["경부선 KTX","호남선 KTX","경전선 KTX","전라선 KTX","동해선 KTX"]
index_list = ['2011','2012','2015','2016','2017','2018','2019']

df_KTX = pd.DataFrame(KTX_data, columns=col_list, index=index_list)
df_KTX


경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011  39060.0     7313     3612      309      NaN
2012  39896.0     6967     6589     1771      NaN
2015  42005.0     6876     6587     1954      NaN
2016  43621.0     6654     6597     2244      NaN
2017  41702.0     5589     9898     3146   2395.0
2018  41266.0    10622     6565     3945   3786.0
2019      NaN     9228     9587     5766   6667.0

In [72]:
df_KTX.index

Index(['2011', '2012', '2015', '2016', '2017', '2018', '2019'], dtype='object')

In [73]:
df_KTX.columns

Index(['경부선 KTX', '호남선 KTX', '경전선 KTX', '전라선 KTX', '동해선 KTX'], dtype='object')

In [74]:
df_KTX.values

array([[39060.,  7313.,  3612.,   309.,    nan],
       [39896.,  6967.,  6589.,  1771.,    nan],
       [42005.,  6876.,  6587.,  1954.,    nan],
       [43621.,  6654.,  6597.,  2244.,    nan],
       [41702.,  5589.,  9898.,  3146.,  2395.],
       [41266., 10622.,  6565.,  3945.,  3786.],
       [   nan,  9228.,  9587.,  5766.,  6667.]])

In [75]:
df_KTX.head()

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011  39060.0     7313     3612      309      NaN
2012  39896.0     6967     6589     1771      NaN
2015  42005.0     6876     6587     1954      NaN
2016  43621.0     6654     6597     2244      NaN
2017  41702.0     5589     9898     3146   2395.0

In [76]:
df_KTX.tail()

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2015  42005.0     6876     6587     1954      NaN
2016  43621.0     6654     6597     2244      NaN
2017  41702.0     5589     9898     3146   2395.0
2018  41266.0    10622     6565     3945   3786.0
2019      NaN     9228     9587     5766   6667.0

In [77]:
df_KTX.head(3)

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011  39060.0     7313     3612      309      NaN
2012  39896.0     6967     6589     1771      NaN
2015  42005.0     6876     6587     1954      NaN