In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [2]:
import numpy as np
import pandas as pd


In [3]:
s=pd.Series(range(10))
s[3]=np.nan
s

0    0.0
1    1.0
2    2.0
3    NaN
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [4]:
s.count() # nan은 제외하고 count

np.int64(9)

In [6]:
np.random.seed(1)
df2=pd.DataFrame(np.random.randint(10,size=(4,8)))
df2

0  1  2  3  4  5  6  7
0  5  8  9  5  0  0  1  7
1  6  9  2  4  5  2  4  2
2  4  7  7  9  1  7  0  6
3  9  9  7  6  9  1  0  1

In [8]:
df2.sum(axis=1)

0    35
1    34
2    41
3    42
dtype: int64

In [10]:
# df2각 열의 합계를 구함
# 8열이므로 결과는 8개의 원소값을 값는 시리즈 반환
df2.sum(axis=0)

0    24
1    33
2    25
3    24
4    15
5    10
6     5
7    16
dtype: int64

In [11]:
df2.sum() # axis 인수 생략하면 기본값이 0이므로 각 열의 합계를 구함

0    24
1    33
2    25
3    24
4    15
5    10
6     5
7    16
dtype: int64

In [12]:
# 각 행의 합계를 표시하는 합계 열을 추가하시오
# 여러번 실행하면 total값까지 누적되어서 잘못된 결과가 발생가능
# df2['total']=df2.sum(axis=1)

df2['total']=df2[[0,1,2,3,4,5,6,7]].sum(axis=1)
df2

0  1  2  3  4  5  6  7  total
0  5  8  9  5  0  0  1  7     35
1  6  9  2  4  5  2  4  2     34
2  4  7  7  9  1  7  0  6     41
3  9  9  7  6  9  1  0  1     42

In [13]:
df2

0  1  2  3  4  5  6  7  total
0  5  8  9  5  0  0  1  7     35
1  6  9  2  4  5  2  4  2     34
2  4  7  7  9  1  7  0  6     41
3  9  9  7  6  9  1  0  1     42

In [14]:
df2.mean(axis=0)


0         6.00
1         8.25
2         6.25
3         6.00
4         3.75
5         2.50
6         1.25
7         4.00
total    38.00
dtype: float64

In [16]:
df2.mean(axis=1)

0    7.777778
1    7.555556
2    9.111111
3    9.333333
dtype: float64

In [17]:
df2.min(axis=0)


0         4
1         7
2         2
3         4
4         0
5         0
6         0
7         1
total    34
dtype: int64

In [18]:
df2.min(axis=1)

0    0
1    2
2    0
3    0
dtype: int64

In [19]:
# 각 열의 최대값
df2.max(axis=0)

0         9
1         9
2         9
3         9
4         9
5         7
6         4
7         7
total    42
dtype: int64

In [20]:
# 각 행의 최대값
df2.max(axis=1)

0    35
1    34
2    41
3    42
dtype: int64

In [21]:
df2.loc['max_data']=df2[[0,1,2,3,4,5,6,7]].max(axis=0)
df2

0    1    2    3    4    5    6    7  total
0         5.0  8.0  9.0  5.0  0.0  0.0  1.0  7.0   35.0
1         6.0  9.0  2.0  4.0  5.0  2.0  4.0  2.0   34.0
2         4.0  7.0  7.0  9.0  1.0  7.0  0.0  6.0   41.0
3         9.0  9.0  7.0  6.0  9.0  1.0  0.0  1.0   42.0
max_data  9.0  9.0  9.0  9.0  9.0  7.0  4.0  7.0    NaN

In [22]:
df2

0    1    2    3    4    5    6    7  total
0         5.0  8.0  9.0  5.0  0.0  0.0  1.0  7.0   35.0
1         6.0  9.0  2.0  4.0  5.0  2.0  4.0  2.0   34.0
2         4.0  7.0  7.0  9.0  1.0  7.0  0.0  6.0   41.0
3         9.0  9.0  7.0  6.0  9.0  1.0  0.0  1.0   42.0
max_data  9.0  9.0  9.0  9.0  9.0  7.0  4.0  7.0    NaN

In [23]:
df2.drop('total',axis=1,inplace=True)
df2

0    1    2    3    4    5    6    7
0         5.0  8.0  9.0  5.0  0.0  0.0  1.0  7.0
1         6.0  9.0  2.0  4.0  5.0  2.0  4.0  2.0
2         4.0  7.0  7.0  9.0  1.0  7.0  0.0  6.0
3         9.0  9.0  7.0  6.0  9.0  1.0  0.0  1.0
max_data  9.0  9.0  9.0  9.0  9.0  7.0  4.0  7.0

In [24]:
df2.drop('max_data',axis=0)
df2

0    1    2    3    4    5    6    7
0  5.0  8.0  9.0  5.0  0.0  0.0  1.0  7.0
1  6.0  9.0  2.0  4.0  5.0  2.0  4.0  2.0
2  4.0  7.0  7.0  9.0  1.0  7.0  0.0  6.0
3  9.0  9.0  7.0  6.0  9.0  1.0  0.0  1.0

0    1    2    3    4    5    6    7
0         5.0  8.0  9.0  5.0  0.0  0.0  1.0  7.0
1         6.0  9.0  2.0  4.0  5.0  2.0  4.0  2.0
2         4.0  7.0  7.0  9.0  1.0  7.0  0.0  6.0
3         9.0  9.0  7.0  6.0  9.0  1.0  0.0  1.0
max_data  9.0  9.0  9.0  9.0  9.0  7.0  4.0  7.0

In [25]:
df2

0    1    2    3    4    5    6    7
0         5.0  8.0  9.0  5.0  0.0  0.0  1.0  7.0
1         6.0  9.0  2.0  4.0  5.0  2.0  4.0  2.0
2         4.0  7.0  7.0  9.0  1.0  7.0  0.0  6.0
3         9.0  9.0  7.0  6.0  9.0  1.0  0.0  1.0
max_data  9.0  9.0  9.0  9.0  9.0  7.0  4.0  7.0

In [26]:
df2.iloc[0,0]=np.nan
df2

0    1    2    3    4    5    6    7
0         NaN  8.0  9.0  5.0  0.0  0.0  1.0  7.0
1         6.0  9.0  2.0  4.0  5.0  2.0  4.0  2.0
2         4.0  7.0  7.0  9.0  1.0  7.0  0.0  6.0
3         9.0  9.0  7.0  6.0  9.0  1.0  0.0  1.0
max_data  9.0  9.0  9.0  9.0  9.0  7.0  4.0  7.0

In [27]:
df2.dropna(axis=0)
df2

0    1    2    3    4    5    6    7
1         6.0  9.0  2.0  4.0  5.0  2.0  4.0  2.0
2         4.0  7.0  7.0  9.0  1.0  7.0  0.0  6.0
3         9.0  9.0  7.0  6.0  9.0  1.0  0.0  1.0
max_data  9.0  9.0  9.0  9.0  9.0  7.0  4.0  7.0

0    1    2    3    4    5    6    7
0         NaN  8.0  9.0  5.0  0.0  0.0  1.0  7.0
1         6.0  9.0  2.0  4.0  5.0  2.0  4.0  2.0
2         4.0  7.0  7.0  9.0  1.0  7.0  0.0  6.0
3         9.0  9.0  7.0  6.0  9.0  1.0  0.0  1.0
max_data  9.0  9.0  9.0  9.0  9.0  7.0  4.0  7.0

In [28]:
df2.dropna(axis=1)
df2

1    2    3    4    5    6    7
0         8.0  9.0  5.0  0.0  0.0  1.0  7.0
1         9.0  2.0  4.0  5.0  2.0  4.0  2.0
2         7.0  7.0  9.0  1.0  7.0  0.0  6.0
3         9.0  7.0  6.0  9.0  1.0  0.0  1.0
max_data  9.0  9.0  9.0  9.0  7.0  4.0  7.0

0    1    2    3    4    5    6    7
0         NaN  8.0  9.0  5.0  0.0  0.0  1.0  7.0
1         6.0  9.0  2.0  4.0  5.0  2.0  4.0  2.0
2         4.0  7.0  7.0  9.0  1.0  7.0  0.0  6.0
3         9.0  9.0  7.0  6.0  9.0  1.0  0.0  1.0
max_data  9.0  9.0  9.0  9.0  9.0  7.0  4.0  7.0

In [29]:
df2.dropna(axis=1,inplace=True)
df2

1    2    3    4    5    6    7
0         8.0  9.0  5.0  0.0  0.0  1.0  7.0
1         9.0  2.0  4.0  5.0  2.0  4.0  2.0
2         7.0  7.0  9.0  1.0  7.0  0.0  6.0
3         9.0  7.0  6.0  9.0  1.0  0.0  1.0
max_data  9.0  9.0  9.0  9.0  7.0  4.0  7.0

In [35]:
df2.iloc[0,0]=np.nan

In [36]:
df2

1    2    3    4    5    6    7
0         NaN  9.0  5.0  0.0  0.0  1.0  7.0
1         9.0  2.0  4.0  5.0  2.0  4.0  2.0
2         7.0  7.0  9.0  1.0  7.0  0.0  6.0
3         9.0  7.0  6.0  9.0  1.0  0.0  1.0
max_data  9.0  9.0  9.0  9.0  7.0  4.0  7.0

In [37]:
df2.fillna(0)
df2

1    2    3    4    5    6    7
0         0.0  9.0  5.0  0.0  0.0  1.0  7.0
1         9.0  2.0  4.0  5.0  2.0  4.0  2.0
2         7.0  7.0  9.0  1.0  7.0  0.0  6.0
3         9.0  7.0  6.0  9.0  1.0  0.0  1.0
max_data  9.0  9.0  9.0  9.0  7.0  4.0  7.0

1    2    3    4    5    6    7
0         NaN  9.0  5.0  0.0  0.0  1.0  7.0
1         9.0  2.0  4.0  5.0  2.0  4.0  2.0
2         7.0  7.0  9.0  1.0  7.0  0.0  6.0
3         9.0  7.0  6.0  9.0  1.0  0.0  1.0
max_data  9.0  9.0  9.0  9.0  7.0  4.0  7.0

In [38]:
df2
df2.fillna(0)

1    2    3    4    5    6    7
0         NaN  9.0  5.0  0.0  0.0  1.0  7.0
1         9.0  2.0  4.0  5.0  2.0  4.0  2.0
2         7.0  7.0  9.0  1.0  7.0  0.0  6.0
3         9.0  7.0  6.0  9.0  1.0  0.0  1.0
max_data  9.0  9.0  9.0  9.0  7.0  4.0  7.0

1    2    3    4    5    6    7
0         0.0  9.0  5.0  0.0  0.0  1.0  7.0
1         9.0  2.0  4.0  5.0  2.0  4.0  2.0
2         7.0  7.0  9.0  1.0  7.0  0.0  6.0
3         9.0  7.0  6.0  9.0  1.0  0.0  1.0
max_data  9.0  9.0  9.0  9.0  7.0  4.0  7.0

In [39]:
df2
df2.fillna(1)

1    2    3    4    5    6    7
0         NaN  9.0  5.0  0.0  0.0  1.0  7.0
1         9.0  2.0  4.0  5.0  2.0  4.0  2.0
2         7.0  7.0  9.0  1.0  7.0  0.0  6.0
3         9.0  7.0  6.0  9.0  1.0  0.0  1.0
max_data  9.0  9.0  9.0  9.0  7.0  4.0  7.0

1    2    3    4    5    6    7
0         1.0  9.0  5.0  0.0  0.0  1.0  7.0
1         9.0  2.0  4.0  5.0  2.0  4.0  2.0
2         7.0  7.0  9.0  1.0  7.0  0.0  6.0
3         9.0  7.0  6.0  9.0  1.0  0.0  1.0
max_data  9.0  9.0  9.0  9.0  7.0  4.0  7.0

In [40]:
df2.fillna(1,inplace=True)

In [41]:
df2

1    2    3    4    5    6    7
0         1.0  9.0  5.0  0.0  0.0  1.0  7.0
1         9.0  2.0  4.0  5.0  2.0  4.0  2.0
2         7.0  7.0  9.0  1.0  7.0  0.0  6.0
3         9.0  7.0  6.0  9.0  1.0  0.0  1.0
max_data  9.0  9.0  9.0  9.0  7.0  4.0  7.0

In [42]:
df2.iloc[0,0]=np.nan
df2

1    2    3    4    5    6    7
0         NaN  9.0  5.0  0.0  0.0  1.0  7.0
1         9.0  2.0  4.0  5.0  2.0  4.0  2.0
2         7.0  7.0  9.0  1.0  7.0  0.0  6.0
3         9.0  7.0  6.0  9.0  1.0  0.0  1.0
max_data  9.0  9.0  9.0  9.0  7.0  4.0  7.0

In [43]:
df2.fillna(0).astype(int)

1  2  3  4  5  6  7
0         0  9  5  0  0  1  7
1         9  2  4  5  2  4  2
2         7  7  9  1  7  0  6
3         9  7  6  9  1  0  1
max_data  9  9  9  9  7  4  7

In [44]:
df2.fillna(0).astype(float)

1    2    3    4    5    6    7
0         0.0  9.0  5.0  0.0  0.0  1.0  7.0
1         9.0  2.0  4.0  5.0  2.0  4.0  2.0
2         7.0  7.0  9.0  1.0  7.0  0.0  6.0
3         9.0  7.0  6.0  9.0  1.0  0.0  1.0
max_data  9.0  9.0  9.0  9.0  7.0  4.0  7.0

In [45]:
df2.fillna(0)[1].astype(int)

0           0
1           9
2           7
3           9
max_data    9
Name: 1, dtype: int64

In [46]:
test_df=df2.fillna(0).astype(float)
test_df

1    2    3    4    5    6    7
0         0.0  9.0  5.0  0.0  0.0  1.0  7.0
1         9.0  2.0  4.0  5.0  2.0  4.0  2.0
2         7.0  7.0  9.0  1.0  7.0  0.0  6.0
3         9.0  7.0  6.0  9.0  1.0  0.0  1.0
max_data  9.0  9.0  9.0  9.0  7.0  4.0  7.0

In [47]:
test_df[1]=test_df[1].astype(int)
test_df

# 열 행 순서여서 1은 열로 취급


1    2    3    4    5    6    7
0         0  9.0  5.0  0.0  0.0  1.0  7.0
1         9  2.0  4.0  5.0  2.0  4.0  2.0
2         7  7.0  9.0  1.0  7.0  0.0  6.0
3         9  7.0  6.0  9.0  1.0  0.0  1.0
max_data  9  9.0  9.0  9.0  7.0  4.0  7.0

In [48]:
df3=pd.DataFrame({
    'a':[1,3,4,3,4],
    'b':[2,3,1,4,5],
    'c':[1,5,2,4,4]
})
df3

a  b  c
0  1  2  1
1  3  3  5
2  4  1  2
3  3  4  4
4  4  5  4

In [49]:
np.sum([1,2,3])

np.int64(6)

In [50]:
np.sum(df3['a'])


np.int64(15)

In [51]:
np.sum(df3['b'])

np.int64(15)

In [52]:
np.sum(df3['c'])

np.int64(16)

In [54]:
for i in ['a','b','c']:
    print(np.sum(df3[i]))

15
15
16


In [55]:
df3.apply(np.sum,0)

a    15
b    15
c    16
dtype: int64

In [56]:
import seaborn as sns

titanic=sns.load_dataset('titanic')

titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [57]:
titanic.tail()

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

In [58]:
titanic[['alive','sex','class']].apply(pd.value_counts,0)

C:\Users\User\AppData\Local\Temp\ipykernel_7444\2950698262.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  titanic[['alive','sex','class']].apply(pd.value_counts,0)
C:\Users\User\AppData\Local\Temp\ipykernel_7444\2950698262.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  titanic[['alive','sex','class']].apply(pd.value_counts,0)
C:\Users\User\AppData\Local\Temp\ipykernel_7444\2950698262.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  titanic[['alive','sex','class']].apply(pd.value_counts,0)


alive    sex  class
First     NaN    NaN  216.0
Second    NaN    NaN  184.0
Third     NaN    NaN  491.0
female    NaN  314.0    NaN
male      NaN  577.0    NaN
no      549.0    NaN    NaN
yes     342.0    NaN    NaN

In [59]:
def diff(x):
    return x.max()-x.min()

In [60]:
df3

a  b  c
0  1  2  1
1  3  3  5
2  4  1  2
3  3  4  4
4  4  5  4

In [61]:
diff(df3['a'])


3

In [62]:
diff(df3['b'])

4

In [63]:
diff(df3['c'])

4

In [64]:
df3.apply(diff,0)

a    3
b    4
c    4
dtype: int64

In [65]:
pd.Series(3)

0    3
dtype: int64

In [66]:
pd.Series(3).max()

3

In [67]:
(lambda x: x.max()-x.min())(df3['a'])

3

In [68]:
df3.apply(lambda x:x.max()-x.min(),0)

a    3
b    4
c    4
dtype: int64

In [70]:
df3.max(axis=0)-df3.min(axis=0)

a    3
b    4
c    4
dtype: int64

In [71]:
np.square([1,2,3])
df3

array([1, 4, 9])

a  b  c
0  1  2  1
1  3  3  5
2  4  1  2
3  3  4  4
4  4  5  4

In [73]:
df3.apply(np.square,0)
df3

a   b   c
0   1   4   1
1   9   9  25
2  16   1   4
3   9  16  16
4  16  25  16

a  b  c
0  1  2  1
1  3  3  5
2  4  1  2
3  3  4  4
4  4  5  4

In [74]:
df3.apply(np.square,0)
df3.apply(np.square,1)

a   b   c
0   1   4   1
1   9   9  25
2  16   1   4
3   9  16  16
4  16  25  16

a   b   c
0   1   4   1
1   9   9  25
2  16   1   4
3   9  16  16
4  16  25  16

In [75]:
ages=[0,0.5,4,6,4,5,2,10,21,23,37,15,38,31,61,20,41,31,100]

In [76]:
data=ages

bins=[0,4,18,25,35,60,100]

labels=['영유아','미성년자','청년','중년','장년','노년']

len(data)

19

In [77]:
cats=pd.cut(data,bins,labels=labels)
cats

[NaN, '영유아', '영유아', '미성년자', '영유아', ..., '노년', '청년', '장년', '중년', '노년']
Length: 19
Categories (6, object): ['영유아' < '미성년자' < '청년' < '중년' < '장년' < '노년']

In [78]:
type(cats)

pandas.core.arrays.categorical.Categorical

In [79]:
cat_list=list(cats)
cat_list

[nan,
 '영유아',
 '영유아',
 '미성년자',
 '영유아',
 '미성년자',
 '영유아',
 '미성년자',
 '청년',
 '청년',
 '장년',
 '미성년자',
 '장년',
 '중년',
 '노년',
 '청년',
 '장년',
 '중년',
 '노년']

In [81]:
test=pd.DataFrame({'나이':ages,'연령대':cat_list})
test

나이   연령대
0     0.0   NaN
1     0.5   영유아
2     4.0   영유아
3     6.0  미성년자
4     4.0   영유아
5     5.0  미성년자
6     2.0   영유아
7    10.0  미성년자
8    21.0    청년
9    23.0    청년
10   37.0    장년
11   15.0  미성년자
12   38.0    장년
13   31.0    중년
14   61.0    노년
15   20.0    청년
16   41.0    장년
17   31.0    중년
18  100.0    노년

In [82]:
test['연령대'].value_counts()

연령대
영유아     4
미성년자    4
청년      3
장년      3
중년      2
노년      2
Name: count, dtype: int64

In [83]:
type(cats)

pandas.core.arrays.categorical.Categorical

In [84]:
cats.categories

Index(['영유아', '미성년자', '청년', '중년', '장년', '노년'], dtype='object')

In [85]:
cats.codes
# 인덱스 위치 정수값이 -1이면 NaN으로 결정되어 결측치가됨


array([-1,  0,  0,  1,  0,  1,  0,  1,  2,  2,  4,  1,  4,  3,  5,  2,  4,
        3,  5], dtype=int8)

In [86]:
np.random.seed(2)
data=np.random.randint(20,size=20)
data

array([ 8, 15, 13,  8, 11, 18, 11,  8,  7,  2, 17, 11, 15,  5,  7,  3,  6,
        4, 10, 11], dtype=int32)

In [89]:
qcat=pd.qcut(data,4,labels=['Q1','Q2','Q3','Q4'])
qcat

['Q2', 'Q4', 'Q4', 'Q2', 'Q3', ..., 'Q1', 'Q1', 'Q1', 'Q3', 'Q3']
Length: 20
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [90]:
np.sort(data)

array([ 2,  3,  4,  5,  6,  7,  7,  8,  8,  8, 10, 11, 11, 11, 11, 13, 15,
       15, 17, 18], dtype=int32)

In [91]:
pd.value_counts(qcat)

C:\Users\User\AppData\Local\Temp\ipykernel_7444\1392370382.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(qcat)


Q1    5
Q2    5
Q3    5
Q4    5
Name: count, dtype: int64

In [92]:
df0=pd.DataFrame(data,columns=['관측수'])

df0['범주']=qcat
df0

관측수  범주
0     8  Q2
1    15  Q4
2    13  Q4
3     8  Q2
4    11  Q3
5    18  Q4
6    11  Q3
7     8  Q2
8     7  Q2
9     2  Q1
10   17  Q4
11   11  Q3
12   15  Q4
13    5  Q1
14    7  Q2
15    3  Q1
16    6  Q1
17    4  Q1
18   10  Q3
19   11  Q3

In [93]:
df3=pd.DataFrame({
    'a':[1,3,4,3,4],
    'b':[2,3,1,4,5],
    'c':[1,5,2,4,4]
})
df3

a  b  c
0  1  2  1
1  3  3  5
2  4  1  2
3  3  4  4
4  4  5  4

In [94]:
df3.set_index('a')
df3

b  c
a      
1  2  1
3  3  5
4  1  2
3  4  4
4  5  4

a  b  c
0  1  2  1
1  3  3  5
2  4  1  2
3  3  4  4
4  4  5  4

In [95]:
df3.set_index('a',inplace=True)

In [96]:
df3

b  c
a      
1  2  1
3  3  5
4  1  2
3  4  4
4  5  4

In [97]:
df3.loc[3]

b  c
a      
3  3  5
3  4  4

In [99]:
df3.reset_index(drop=True)

b  c
0  2  1
1  3  5
2  1  2
3  4  4
4  5  4

In [98]:
df3.reset_index()
df3

a  b  c
0  1  2  1
1  3  3  5
2  4  1  2
3  3  4  4
4  4  5  4

b  c
a      
1  2  1
3  3  5
4  1  2
3  4  4
4  5  4

In [100]:
df3.reset_index(drop=True,inplace=True)
df3

b  c
0  2  1
1  3  5
2  1  2
3  4  4
4  5  4

In [102]:
df3.rename(index={0:'1반',1:'2반'})

학생  c
1반   2  1
2반   3  5
2    1  2
3    4  4
4    5  4

In [103]:
df3.rename(columns={'b':'학생'},inplace=True)

In [104]:
df3

학생  c
0   2  1
1   3  5
2   1  2
3   4  4
4   5  4

In [105]:
a=[1,2,3,4]

In [106]:
a=[1,2,3,4]
result=[]

for num in a:
    result.append(num*2)

result

[2, 4, 6, 8]

In [107]:
result=[num*2 for num in a]
result

[2, 4, 6, 8]

In [108]:
test=[]
for i in range(1,5):
    test.append('id_'+str(i))
test

['id_1', 'id_2', 'id_3', 'id_4']

In [109]:
test=['id_'+str(i) for i in range(1,5)]
test

['id_1', 'id_2', 'id_3', 'id_4']