In [1]:
import pandas as pd
import numpy as np

In [2]:
s=pd.Series([1,2,3])
s

0    1
1    2
2    3
dtype: int64

In [3]:
s=pd.Series((1.0,2.0,3.0))
s

0    1.0
1    2.0
2    3.0
dtype: float64

In [4]:
s2=pd.Series(['a','a','c'])
s2

0    a
1    a
2    c
dtype: object

In [5]:
s_1=pd.Series(['a',1,3.0])
s_1

0      a
1      1
2    3.0
dtype: object

In [6]:
s=pd.Series(range(10,14))
s

0    10
1    11
2    12
3    13
dtype: int64

In [7]:
range(10,14)

range(10, 14)

In [8]:
np.arange(200)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [9]:
s3=pd.Series(np.arange(200))
s3

0        0
1        1
2        2
3        3
4        4
      ... 
195    195
196    196
197    197
198    198
199    199
Length: 200, dtype: int64

In [10]:
s=pd.Series([1,2,3,np.nan,6,8])
s

0    1.0
1    2.0
2    3.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [11]:
s=pd.Series([10,20,30],index=[1,2,3])
s

1    10
2    20
3    30
dtype: int64

In [12]:
s=pd.Series([95,100,88],index=['홍길동','이몽룡','성춘향'])
s

홍길동     95
이몽룡    100
성춘향     88
dtype: int64

In [13]:
s0=pd.Series([10,20,30],index=[1,2,3])
s0

1    10
2    20
3    30
dtype: int64

In [14]:
s0.index

Index([1, 2, 3], dtype='int64')

In [15]:
s00=pd.Series([1,2,3])
s00.index

RangeIndex(start=0, stop=3, step=1)

In [16]:
s=pd.Series([9904312,3448737,289045,2466052],
            index=["서울","부산","인천","대구"])
s.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [17]:
s.index.name='광역시'
s

광역시
서울    9904312
부산    3448737
인천     289045
대구    2466052
dtype: int64

In [18]:
s.index

Index(['서울', '부산', '인천', '대구'], dtype='object', name='광역시')

In [19]:
s.values

array([9904312, 3448737,  289045, 2466052])

In [20]:
s.name='인구'
s

광역시
서울    9904312
부산    3448737
인천     289045
대구    2466052
Name: 인구, dtype: int64

In [22]:
print(s.index)


Index(['서울', '부산', '인천', '대구'], dtype='object', name='광역시')


In [23]:
s['인천']

np.int64(289045)

In [24]:
s[2]

C:\Users\User\AppData\Local\Temp\ipykernel_14752\2635755408.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[2]


np.int64(289045)

In [25]:
s03=pd.Series([1,2,3],index=[1,2,3])
s03

1    1
2    2
3    3
dtype: int64

In [28]:
s03[1]

np.int64(1)

In [29]:
s['부산']

np.int64(3448737)

In [30]:
s[3]

C:\Users\User\AppData\Local\Temp\ipykernel_14752\3172538273.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[3]


np.int64(2466052)

In [31]:
s['대구']

np.int64(2466052)

In [32]:
s

광역시
서울    9904312
부산    3448737
인천     289045
대구    2466052
Name: 인구, dtype: int64

In [33]:
print(s)

광역시
서울    9904312
부산    3448737
인천     289045
대구    2466052
Name: 인구, dtype: int64


In [34]:
s[0],s[3],s[1]

C:\Users\User\AppData\Local\Temp\ipykernel_14752\2878105266.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[0],s[3],s[1]


(np.int64(9904312), np.int64(2466052), np.int64(3448737))

In [35]:
s[[0,3,1]]

C:\Users\User\AppData\Local\Temp\ipykernel_14752\181403017.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[[0,3,1]]


광역시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [39]:

s[[1,2]]


C:\Users\User\AppData\Local\Temp\ipykernel_14752\1143378462.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[[1,2]]


광역시
부산    3448737
인천     289045
Name: 인구, dtype: int64

In [40]:
s[['부산','인천']]


광역시
부산    3448737
인천     289045
Name: 인구, dtype: int64

In [41]:
s[1:3]

광역시
부산    3448737
인천     289045
Name: 인구, dtype: int64

In [42]:
s["부산":"대구"]

광역시
부산    3448737
인천     289045
대구    2466052
Name: 인구, dtype: int64

In [43]:
s_01=pd.Series([100,200,300,400],index=[1,2,3,4])
print(s_01)

1    100
2    200
3    300
4    400
dtype: int64


In [44]:
s_01[[2,3,4]]

2    200
3    300
4    400
dtype: int64

In [45]:
s_01[2:4]

3    300
4    400
dtype: int64

In [46]:
s0=pd.Series(range(3),index=['a','b','c'])
s0

a    0
b    1
c    2
dtype: int64

In [49]:
s0['a']


np.int64(0)

In [50]:
s0.a

np.int64(0)

In [51]:
print(s)

광역시
서울    9904312
부산    3448737
인천     289045
대구    2466052
Name: 인구, dtype: int64


In [52]:
s['서울']
s.서울

np.int64(9904312)

In [53]:
s['서울']=10000000
s['서울']

np.int64(10000000)

In [55]:
s

광역시
서울    10000000
부산     3448737
인천      289045
대구     2466052
Name: 인구, dtype: int64

In [56]:
print(s.index)
s1=pd.Series(np.arange(4),s.index)
s1

Index(['서울', '부산', '인천', '대구'], dtype='object', name='광역시')


광역시
서울    0
부산    1
인천    2
대구    3
dtype: int64

In [57]:
s

광역시
서울    10000000
부산     3448737
인천      289045
대구     2466052
Name: 인구, dtype: int64

In [77]:
s[(s>250e4) & (s<500e4)]

광역시
부산    3448737
Name: 인구, dtype: int64

In [58]:
pd.Series([1,2,3])+4

0    5
1    6
2    7
dtype: int64

In [59]:
print(s)

광역시
서울    10000000
부산     3448737
인천      289045
대구     2466052
Name: 인구, dtype: int64


In [60]:
s/1000000

광역시
서울    10.000000
부산     3.448737
인천     0.289045
대구     2.466052
Name: 인구, dtype: float64

In [61]:
s

광역시
서울    10000000
부산     3448737
인천      289045
대구     2466052
Name: 인구, dtype: int64

In [66]:
print(s)

광역시
서울    10000000
부산     3448737
인천      289045
대구     2466052
Name: 인구, dtype: int64


In [67]:
s0=pd.Series(np.arange(10),np.arange(10)+1)
s0

1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int64

In [68]:
s0>5

1     False
2     False
3     False
4     False
5     False
6     False
7      True
8      True
9      True
10     True
dtype: bool

In [69]:
s0[s0>5]

7     6
8     7
9     8
10    9
dtype: int64

In [70]:
s0[s0%2==0]

1    0
3    2
5    4
7    6
9    8
dtype: int64

In [71]:
s0

1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int64

In [72]:
s0.index>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [73]:
s0[s0.index>5]

6     5
7     6
8     7
9     8
10    9
dtype: int64

In [74]:
s0[(s0>5) & (s0<8)]

7    6
8    7
dtype: int64

In [76]:
(s0>=7).sum()

np.int64(3)

In [78]:
(s0[s0>=7]).sum()

np.int64(24)

In [79]:
num_s1=pd.Series([1,2,3,4],index=['a','b','c','d'])
num_s1

a    1
b    2
c    3
d    4
dtype: int64

In [80]:
num_s2=pd.Series([5,6,7,8],index=['b','c','d','a'])
num_s2

b    5
c    6
d    7
a    8
dtype: int64

In [82]:
num_s1+num_s2

a     9
b     7
c     9
d    11
dtype: int64

In [83]:
num_s3=pd.Series([5,6,7,8],index=['e','b','f','g'])
num_s4=pd.Series([1,2,3,4],index=['a','b','c','d'])

In [84]:
num_s3-num_s4

a    NaN
b    4.0
c    NaN
d    NaN
e    NaN
f    NaN
g    NaN
dtype: float64

In [85]:
num_s3.values-num_s4.values

array([4, 4, 4, 4])

In [86]:
s

광역시
서울    10000000
부산     3448737
인천      289045
대구     2466052
Name: 인구, dtype: int64

In [87]:
'서울' in s

True

In [88]:
'대전' in s

False

In [89]:
'대전' not in s

True

In [90]:
s.items()

In [91]:
list(s.items())

[('서울', 10000000), ('부산', 3448737), ('인천', 289045), ('대구', 2466052)]

In [92]:
for k,v in s.items():
    print("%s=%d" % (k,v))

서울=10000000
부산=3448737
인천=289045
대구=2466052


In [93]:
scores={"홍길동":96,"이몽룡":100,"성춘향":88}
s=pd.Series(scores)
s

홍길동     96
이몽룡    100
성춘향     88
dtype: int64

In [94]:
city={'서울':9631482,'부산':3393190,'인천':2632035,'대전':1490158}
s=pd.Series(city)
s

서울    9631482
부산    3393190
인천    2632035
대전    1490158
dtype: int64

In [97]:
city={'서울':9631482,'부산':3393191,'인천':2632035,'대전':1490158}
s=pd.Series(city,index=city.keys())
s

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [98]:
s=pd.Series(city,index=['부산','인천','서울','대전'])
s

부산    3393191
인천    2632035
서울    9631482
대전    1490158
dtype: int64

In [99]:
s

부산    3393191
인천    2632035
서울    9631482
대전    1490158
dtype: int64

In [101]:
s['부산']=1630000
s

부산    1630000
인천    2632035
서울    9631482
대전    1490158
dtype: int64

In [104]:
del s['서울']
s

부산    1630000
인천    2632035
대전    1490158
dtype: int64

In [105]:
s['대구']=1875000
s

부산    1630000
인천    2632035
대전    1490158
대구    1875000
dtype: int64

In [108]:
s1=pd.Series([1,1,2,1,2,2,2,1,1,3,3,4,5,5,7,np.nan])
s1

0     1.0
1     1.0
2     2.0
3     1.0
4     2.0
5     2.0
6     2.0
7     1.0
8     1.0
9     3.0
10    3.0
11    4.0
12    5.0
13    5.0
14    7.0
15    NaN
dtype: float64

In [109]:
len(s1)

16

In [110]:
s1.size

16

In [111]:
s1.shape

(16,)

In [112]:
s1.unique()

array([ 1.,  2.,  3.,  4.,  5.,  7., nan])

In [113]:
s1.count()

np.int64(15)

In [115]:
a=np.array([2,2,2,2,np.nan])
print(a.mean())

nan


In [116]:
b=pd.Series(a)
print(b)
b.mean()

0    2.0
1    2.0
2    2.0
3    2.0
4    NaN
dtype: float64


np.float64(2.0)

In [117]:
s1

0     1.0
1     1.0
2     2.0
3     1.0
4     2.0
5     2.0
6     2.0
7     1.0
8     1.0
9     3.0
10    3.0
11    4.0
12    5.0
13    5.0
14    7.0
15    NaN
dtype: float64

In [118]:
s1.mean()

np.float64(2.6666666666666665)

In [119]:
s1.value_counts()

1.0    5
2.0    4
3.0    2
5.0    2
4.0    1
7.0    1
Name: count, dtype: int64

In [121]:
index_date=['2018-10-07','2018-10-08','2018-10-09','2018-10-10']
s4=pd.Series([200,195,np.nan,205],index=index_date)
s4

2018-10-07    200.0
2018-10-08    195.0
2018-10-09      NaN
2018-10-10    205.0
dtype: float64

In [122]:
type(s4.index[0])

str

In [123]:
pd.date_range(start='2018-10-01',end='2018-10-20')


DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06', '2018-10-07', '2018-10-08',
               '2018-10-09', '2018-10-10', '2018-10-11', '2018-10-12',
               '2018-10-13', '2018-10-14', '2018-10-15', '2018-10-16',
               '2018-10-17', '2018-10-18', '2018-10-19', '2018-10-20'],
              dtype='datetime64[ns]', freq='D')

In [124]:
pd.date_range(start='2018-10-01',end='2018-10-20',freq='d')


DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06', '2018-10-07', '2018-10-08',
               '2018-10-09', '2018-10-10', '2018-10-11', '2018-10-12',
               '2018-10-13', '2018-10-14', '2018-10-15', '2018-10-16',
               '2018-10-17', '2018-10-18', '2018-10-19', '2018-10-20'],
              dtype='datetime64[ns]', freq='D')

In [125]:
pd.date_range(start='2018-10-01',end='2018-10-20',freq='3D')

DatetimeIndex(['2018-10-01', '2018-10-04', '2018-10-07', '2018-10-10',
               '2018-10-13', '2018-10-16', '2018-10-19'],
              dtype='datetime64[ns]', freq='3D')

In [126]:
pd.date_range(start='2018-10-01',end='2018-10-20',freq='w')

C:\Users\User\AppData\Local\Temp\ipykernel_14752\673303500.py:1: FutureWarning: 'w' is deprecated and will be removed in a future version, please use 'W' instead.
  pd.date_range(start='2018-10-01',end='2018-10-20',freq='w')


DatetimeIndex(['2018-10-07', '2018-10-14'], dtype='datetime64[ns]', freq='W-SUN')

In [127]:
pd.date_range(start='2018-10-01',periods=4,freq='w')

C:\Users\User\AppData\Local\Temp\ipykernel_14752\4077176127.py:1: FutureWarning: 'w' is deprecated and will be removed in a future version, please use 'W' instead.
  pd.date_range(start='2018-10-01',periods=4,freq='w')


DatetimeIndex(['2018-10-07', '2018-10-14', '2018-10-21', '2018-10-28'], dtype='datetime64[ns]', freq='W-SUN')

In [128]:
pd.date_range(start='2018-10-01',periods=4,freq='m')

C:\Users\User\AppData\Local\Temp\ipykernel_14752\4232853345.py:1: FutureWarning: 'm' is deprecated and will be removed in a future version, please use 'ME' instead.
  pd.date_range(start='2018-10-01',periods=4,freq='m')


DatetimeIndex(['2018-10-31', '2018-11-30', '2018-12-31', '2019-01-31'], dtype='datetime64[ns]', freq='ME')

In [129]:
pd.date_range(start='2018-10-01',periods=4,freq='M')

C:\Users\User\AppData\Local\Temp\ipykernel_14752\704418096.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  pd.date_range(start='2018-10-01',periods=4,freq='M')


DatetimeIndex(['2018-10-31', '2018-11-30', '2018-12-31', '2019-01-31'], dtype='datetime64[ns]', freq='ME')

In [130]:
pd.date_range(start='2018-10-01',periods=4,freq='MS')

DatetimeIndex(['2018-10-01', '2018-11-01', '2018-12-01', '2019-01-01'], dtype='datetime64[ns]', freq='MS')

In [131]:
pd.date_range(start='2018-10-01',periods=12,freq='2BM')

C:\Users\User\AppData\Local\Temp\ipykernel_14752\1631065857.py:1: FutureWarning: 'BM' is deprecated and will be removed in a future version, please use 'BME' instead.
  pd.date_range(start='2018-10-01',periods=12,freq='2BM')


DatetimeIndex(['2018-10-31', '2018-12-31', '2019-02-28', '2019-04-30',
               '2019-06-28', '2019-08-30', '2019-10-31', '2019-12-31',
               '2020-02-28', '2020-04-30', '2020-06-30', '2020-08-31'],
              dtype='datetime64[ns]', freq='2BME')

In [132]:
pd.date_range(start='2018-10-01',periods=4,freq='QS')

DatetimeIndex(['2018-10-01', '2019-01-01', '2019-04-01', '2019-07-01'], dtype='datetime64[ns]', freq='QS-JAN')

In [133]:
pd.date_range(start='2018-10-01',periods=4,freq='AS')

C:\Users\User\AppData\Local\Temp\ipykernel_14752\1488287318.py:1: FutureWarning: 'AS' is deprecated and will be removed in a future version, please use 'YS' instead.
  pd.date_range(start='2018-10-01',periods=4,freq='AS')


DatetimeIndex(['2019-01-01', '2020-01-01', '2021-01-01', '2022-01-01'], dtype='datetime64[ns]', freq='YS-JAN')

In [134]:
pd.date_range(start='2018-01-01',periods=4,freq='AS')

C:\Users\User\AppData\Local\Temp\ipykernel_14752\4247004424.py:1: FutureWarning: 'AS' is deprecated and will be removed in a future version, please use 'YS' instead.
  pd.date_range(start='2018-01-01',periods=4,freq='AS')


DatetimeIndex(['2018-01-01', '2019-01-01', '2020-01-01', '2021-01-01'], dtype='datetime64[ns]', freq='YS-JAN')

In [136]:
pd.date_range(start='2018-1-20 08:00',periods=10,freq='H')

C:\Users\User\AppData\Local\Temp\ipykernel_14752\3341344686.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  pd.date_range(start='2018-1-20 08:00',periods=10,freq='H')


DatetimeIndex(['2018-01-20 08:00:00', '2018-01-20 09:00:00',
               '2018-01-20 10:00:00', '2018-01-20 11:00:00',
               '2018-01-20 12:00:00', '2018-01-20 13:00:00',
               '2018-01-20 14:00:00', '2018-01-20 15:00:00',
               '2018-01-20 16:00:00', '2018-01-20 17:00:00'],
              dtype='datetime64[ns]', freq='h')

In [137]:
pd.date_range(start='2018-1-20 08:00',periods=10,freq='BH')

C:\Users\User\AppData\Local\Temp\ipykernel_14752\1724364077.py:1: FutureWarning: 'BH' is deprecated and will be removed in a future version, please use 'bh' instead.
  pd.date_range(start='2018-1-20 08:00',periods=10,freq='BH')


DatetimeIndex(['2018-01-22 09:00:00', '2018-01-22 10:00:00',
               '2018-01-22 11:00:00', '2018-01-22 12:00:00',
               '2018-01-22 13:00:00', '2018-01-22 14:00:00',
               '2018-01-22 15:00:00', '2018-01-22 16:00:00',
               '2018-01-23 09:00:00', '2018-01-23 10:00:00'],
              dtype='datetime64[ns]', freq='bh')

In [138]:
pd.date_range(start='2018-1-20 08:00',periods=10,freq='30min')

DatetimeIndex(['2018-01-20 08:00:00', '2018-01-20 08:30:00',
               '2018-01-20 09:00:00', '2018-01-20 09:30:00',
               '2018-01-20 10:00:00', '2018-01-20 10:30:00',
               '2018-01-20 11:00:00', '2018-01-20 11:30:00',
               '2018-01-20 12:00:00', '2018-01-20 12:30:00'],
              dtype='datetime64[ns]', freq='30min')

In [139]:
pd.date_range(start='2018-1-20 08:00',periods=10,freq='10S')

C:\Users\User\AppData\Local\Temp\ipykernel_14752\2818923233.py:1: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  pd.date_range(start='2018-1-20 08:00',periods=10,freq='10S')


DatetimeIndex(['2018-01-20 08:00:00', '2018-01-20 08:00:10',
               '2018-01-20 08:00:20', '2018-01-20 08:00:30',
               '2018-01-20 08:00:40', '2018-01-20 08:00:50',
               '2018-01-20 08:01:00', '2018-01-20 08:01:10',
               '2018-01-20 08:01:20', '2018-01-20 08:01:30'],
              dtype='datetime64[ns]', freq='10s')